pip install numpy

**Numpy**

1) Numpy Stands for Numerical Python, which consist of single &      multidimesional array object.

2) We can do mathematical & logical operations on array of Numpy.

3) Operation related to linear algebra, statistics and log can        also be done with the help of numpy.

4) We can do matrix calculations as well on Numpy.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.2'

In [3]:
arr = np.array([10,20,30,40,50,60,70])

In [4]:
print(arr)

[10 20 30 40 50 60 70]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([
 [10,20,30,40,50,60,70],
 [100,200,300,400,500,600,700],
 [1000,2000,3000,4000,5000,6000,7000]
])

In [9]:
arr2

array([[  10,   20,   30,   40,   50,   60,   70],
       [ 100,  200,  300,  400,  500,  600,  700],
       [1000, 2000, 3000, 4000, 5000, 6000, 7000]])

In [10]:
arr2.shape

(3, 7)

In [11]:
arr

array([10, 20, 30, 40, 50, 60, 70])

In [12]:
arr.shape

(7,)

In [13]:
arr3 = np.array([
    [10,20,30],
    [40,50,60]
])

In [14]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
arr3.shape

(2, 3)

In [17]:
arr3.shape = (3,2)

In [18]:
arr3

array([[10, 20],
       [30, 40],
       [50, 60]])

In [19]:
range(1,10)

range(1, 10)

In [20]:
num = np.arange(1,31)

In [21]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [22]:
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
np.arange(478448484,478449876)

array([478448484, 478448485, 478448486, ..., 478449873, 478449874,
       478449875])

In [24]:
np.arange(1,51,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [30]:
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
arr5 = np.arange(0,30).reshape(5,6)

In [32]:
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
zeros = np.zeros(10).reshape(5,2)

In [35]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
ones = np.ones(10).reshape(5,2)

In [39]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://miro.medium.com/max/1330/1*s6gKy2DZ_300dgAeHPgjkQ.png" widht="300" height="300">

In [40]:
new_ones = np.ones(10,dtype=np.int16).reshape(5,2)

In [41]:
new_ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [44]:
np.ones(10).reshape(5,2)*4

array([[4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.]])

In [52]:
data = np.linspace(1,3,100)

In [53]:
data

array([1.        , 1.02020202, 1.04040404, 1.06060606, 1.08080808,
       1.1010101 , 1.12121212, 1.14141414, 1.16161616, 1.18181818,
       1.2020202 , 1.22222222, 1.24242424, 1.26262626, 1.28282828,
       1.3030303 , 1.32323232, 1.34343434, 1.36363636, 1.38383838,
       1.4040404 , 1.42424242, 1.44444444, 1.46464646, 1.48484848,
       1.50505051, 1.52525253, 1.54545455, 1.56565657, 1.58585859,
       1.60606061, 1.62626263, 1.64646465, 1.66666667, 1.68686869,
       1.70707071, 1.72727273, 1.74747475, 1.76767677, 1.78787879,
       1.80808081, 1.82828283, 1.84848485, 1.86868687, 1.88888889,
       1.90909091, 1.92929293, 1.94949495, 1.96969697, 1.98989899,
       2.01010101, 2.03030303, 2.05050505, 2.07070707, 2.09090909,
       2.11111111, 2.13131313, 2.15151515, 2.17171717, 2.19191919,
       2.21212121, 2.23232323, 2.25252525, 2.27272727, 2.29292929,
       2.31313131, 2.33333333, 2.35353535, 2.37373737, 2.39393939,
       2.41414141, 2.43434343, 2.45454545, 2.47474747, 2.49494

In [54]:
np.logspace(1,10,200)

array([1.00000000e+01, 1.10975250e+01, 1.23155060e+01, 1.36671636e+01,
       1.51671689e+01, 1.68318035e+01, 1.86791360e+01, 2.07292178e+01,
       2.30043012e+01, 2.55290807e+01, 2.83309610e+01, 3.14403547e+01,
       3.48910121e+01, 3.87203878e+01, 4.29700470e+01, 4.76861170e+01,
       5.29197874e+01, 5.87278661e+01, 6.51733960e+01, 7.23263390e+01,
       8.02643352e+01, 8.90735464e+01, 9.88495905e+01, 1.09698580e+02,
       1.21738273e+02, 1.35099352e+02, 1.49926843e+02, 1.66381689e+02,
       1.84642494e+02, 2.04907469e+02, 2.27396575e+02, 2.52353917e+02,
       2.80050389e+02, 3.10786619e+02, 3.44896226e+02, 3.82749448e+02,
       4.24757155e+02, 4.71375313e+02, 5.23109931e+02, 5.80522552e+02,
       6.44236351e+02, 7.14942899e+02, 7.93409667e+02, 8.80488358e+02,
       9.77124154e+02, 1.08436597e+03, 1.20337784e+03, 1.33545156e+03,
       1.48202071e+03, 1.64467618e+03, 1.82518349e+03, 2.02550194e+03,
       2.24780583e+03, 2.49450814e+03, 2.76828663e+03, 3.07211300e+03,
      

## Indexing & slicing 

In [56]:
arr_1 = np.arange(10,20)

In [57]:
arr_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
arr_1[0]

10

In [59]:
arr_1[1]

11

In [60]:
arr_1[-1]

19

In [61]:
arr_1[3:8]

array([13, 14, 15, 16, 17])

In [66]:
arr6 = np.array([
    [10,20,30,40,50,60],
    [70,80,90,100,110,120],
    [100,200,300,400,500,600],
    [1000,2000,3000,4000,5000,6000]
])

In [63]:
arr6

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [65]:
arr6[0:2,1:3]

array([[20, 30],
       [80, 90]])

In [67]:
arr6

array([[  10,   20,   30,   40,   50,   60],
       [  70,   80,   90,  100,  110,  120],
       [ 100,  200,  300,  400,  500,  600],
       [1000, 2000, 3000, 4000, 5000, 6000]])

In [70]:
arr6[0:4:3,0:3]

array([[  10,   20,   30],
       [1000, 2000, 3000]])

In [73]:
arr6[1:4:2,1:6:2]

array([[  80,  100,  120],
       [2000, 4000, 6000]])

In [74]:
arr7 = np.arange(100,190,10).reshape(3,3)

In [75]:
arr7

array([[100, 110, 120],
       [130, 140, 150],
       [160, 170, 180]])

In [76]:
np.diag(arr7)

array([100, 140, 180])

In [77]:
arr8 = np.array([10,20,30,40])
arr9 = np.array([100,200,300,400])

In [78]:
arr8

array([10, 20, 30, 40])

In [79]:
arr9

array([100, 200, 300, 400])

In [80]:
arr8+arr9

array([110, 220, 330, 440])

In [81]:
arr10 = np.array([10,20,30,40])
arr11 = np.array([100,200,300,400,500])

In [82]:
arr10+arr11

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [83]:
arr8 - arr9

array([ -90, -180, -270, -360])

In [84]:
arr9-arr8

array([ 90, 180, 270, 360])

In [85]:
arr8*arr9

array([ 1000,  4000,  9000, 16000])

In [86]:
arr8/arr9

array([0.1, 0.1, 0.1, 0.1])

In [87]:
arr9/arr8

array([10., 10., 10., 10.])

In [88]:
arr8 % arr9

array([10, 20, 30, 40])

## multidimension array calc

In [89]:
m1 = np.array([
    [0,0,0],
    [10,10,10],
    [20,20,20],
    [30,30,30]
])

In [90]:
m1

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [91]:
m2 = np.array([1,2,3])

In [92]:
m2

array([1, 2, 3])

In [93]:
m1+m2

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])