pip install numpy

**Numpy**

1) Numpy Stands for Numerical Python, which consist of single &      multidimesional array object.

2) We can do mathematical & logical operations on array of Numpy.

3) Operation related to linear algebra, statistics and log can        also be done with the help of numpy.

4) We can do matrix calculations as well on Numpy.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.2'

In [3]:
arr = np.array([10,20,30,40,50,60,70])

In [4]:
print(arr)

[10 20 30 40 50 60 70]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([
 [10,20,30,40,50,60,70],
 [100,200,300,400,500,600,700],
 [1000,2000,3000,4000,5000,6000,7000]
])

In [9]:
arr2

array([[  10,   20,   30,   40,   50,   60,   70],
       [ 100,  200,  300,  400,  500,  600,  700],
       [1000, 2000, 3000, 4000, 5000, 6000, 7000]])

In [10]:
arr2.shape

(3, 7)

In [11]:
arr

array([10, 20, 30, 40, 50, 60, 70])

In [12]:
arr.shape

(7,)

In [13]:
arr3 = np.array([
    [10,20,30],
    [40,50,60]
])

In [14]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
arr3.shape

(2, 3)

In [17]:
arr3.shape = (3,2)

In [18]:
arr3

array([[10, 20],
       [30, 40],
       [50, 60]])

In [19]:
range(1,10)

range(1, 10)

In [20]:
num = np.arange(1,31)

In [21]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [22]:
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
np.arange(478448484,478449876)

array([478448484, 478448485, 478448486, ..., 478449873, 478449874,
       478449875])

In [24]:
np.arange(1,51,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [30]:
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
arr5 = np.arange(0,30).reshape(5,6)

In [32]:
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
zeros = np.zeros(10).reshape(5,2)

In [35]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
ones = np.ones(10).reshape(5,2)

In [39]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://miro.medium.com/max/1330/1*s6gKy2DZ_300dgAeHPgjkQ.png" widht="300" height="300">

In [40]:
new_ones = np.ones(10,dtype=np.int16).reshape(5,2)

In [41]:
new_ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [44]:
np.ones(10).reshape(5,2)*4

array([[4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.],
       [4., 4.]])

In [52]:
data = np.linspace(1,3,100)

In [53]:
data

array([1.        , 1.02020202, 1.04040404, 1.06060606, 1.08080808,
       1.1010101 , 1.12121212, 1.14141414, 1.16161616, 1.18181818,
       1.2020202 , 1.22222222, 1.24242424, 1.26262626, 1.28282828,
       1.3030303 , 1.32323232, 1.34343434, 1.36363636, 1.38383838,
       1.4040404 , 1.42424242, 1.44444444, 1.46464646, 1.48484848,
       1.50505051, 1.52525253, 1.54545455, 1.56565657, 1.58585859,
       1.60606061, 1.62626263, 1.64646465, 1.66666667, 1.68686869,
       1.70707071, 1.72727273, 1.74747475, 1.76767677, 1.78787879,
       1.80808081, 1.82828283, 1.84848485, 1.86868687, 1.88888889,
       1.90909091, 1.92929293, 1.94949495, 1.96969697, 1.98989899,
       2.01010101, 2.03030303, 2.05050505, 2.07070707, 2.09090909,
       2.11111111, 2.13131313, 2.15151515, 2.17171717, 2.19191919,
       2.21212121, 2.23232323, 2.25252525, 2.27272727, 2.29292929,
       2.31313131, 2.33333333, 2.35353535, 2.37373737, 2.39393939,
       2.41414141, 2.43434343, 2.45454545, 2.47474747, 2.49494

In [54]:
np.logspace(1,10,200)

array([1.00000000e+01, 1.10975250e+01, 1.23155060e+01, 1.36671636e+01,
       1.51671689e+01, 1.68318035e+01, 1.86791360e+01, 2.07292178e+01,
       2.30043012e+01, 2.55290807e+01, 2.83309610e+01, 3.14403547e+01,
       3.48910121e+01, 3.87203878e+01, 4.29700470e+01, 4.76861170e+01,
       5.29197874e+01, 5.87278661e+01, 6.51733960e+01, 7.23263390e+01,
       8.02643352e+01, 8.90735464e+01, 9.88495905e+01, 1.09698580e+02,
       1.21738273e+02, 1.35099352e+02, 1.49926843e+02, 1.66381689e+02,
       1.84642494e+02, 2.04907469e+02, 2.27396575e+02, 2.52353917e+02,
       2.80050389e+02, 3.10786619e+02, 3.44896226e+02, 3.82749448e+02,
       4.24757155e+02, 4.71375313e+02, 5.23109931e+02, 5.80522552e+02,
       6.44236351e+02, 7.14942899e+02, 7.93409667e+02, 8.80488358e+02,
       9.77124154e+02, 1.08436597e+03, 1.20337784e+03, 1.33545156e+03,
       1.48202071e+03, 1.64467618e+03, 1.82518349e+03, 2.02550194e+03,
       2.24780583e+03, 2.49450814e+03, 2.76828663e+03, 3.07211300e+03,
      

## Indexing & slicing 

In [56]:
arr_1 = np.arange(10,20)

In [57]:
arr_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
arr_1[0]

10

In [59]:
arr_1[1]

11

In [60]:
arr_1[-1]

19

In [61]:
arr_1[3:8]

array([13, 14, 15, 16, 17])

In [66]:
arr6 = np.array([
    [10,20,30,40,50,60],
    [70,80,90,100,110,120],
    [100,200,300,400,500,600],
    [1000,2000,3000,4000,5000,6000]
])

In [63]:
arr6

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [65]:
arr6[0:2,1:3]

array([[20, 30],
       [80, 90]])

In [67]:
arr6

array([[  10,   20,   30,   40,   50,   60],
       [  70,   80,   90,  100,  110,  120],
       [ 100,  200,  300,  400,  500,  600],
       [1000, 2000, 3000, 4000, 5000, 6000]])

In [70]:
arr6[0:4:3,0:3]

array([[  10,   20,   30],
       [1000, 2000, 3000]])

In [73]:
arr6[1:4:2,1:6:2]

array([[  80,  100,  120],
       [2000, 4000, 6000]])

In [74]:
arr7 = np.arange(100,190,10).reshape(3,3)

In [75]:
arr7

array([[100, 110, 120],
       [130, 140, 150],
       [160, 170, 180]])

In [76]:
np.diag(arr7)

array([100, 140, 180])

In [77]:
arr8 = np.array([10,20,30,40])
arr9 = np.array([100,200,300,400])

In [78]:
arr8

array([10, 20, 30, 40])

In [79]:
arr9

array([100, 200, 300, 400])

In [80]:
arr8+arr9

array([110, 220, 330, 440])

In [81]:
arr10 = np.array([10,20,30,40])
arr11 = np.array([100,200,300,400,500])

In [82]:
arr10+arr11

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [83]:
arr8 - arr9

array([ -90, -180, -270, -360])

In [84]:
arr9-arr8

array([ 90, 180, 270, 360])

In [85]:
arr8*arr9

array([ 1000,  4000,  9000, 16000])

In [86]:
arr8/arr9

array([0.1, 0.1, 0.1, 0.1])

In [87]:
arr9/arr8

array([10., 10., 10., 10.])

In [88]:
arr8 % arr9

array([10, 20, 30, 40])

## multidimension array calc

In [89]:
m1 = np.array([
    [0,0,0],
    [10,10,10],
    [20,20,20],
    [30,30,30]
])

In [90]:
m1

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [91]:
m2 = np.array([1,2,3])

In [92]:
m2

array([1, 2, 3])

In [93]:
m1+m2

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## comparison operations in numpy

In [2]:
mul_d = np.arange(1,21).reshape(5,4)

In [3]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [4]:
mul_d > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
mul_d[mul_d > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [8]:
mul_d[2][2]

11

In [9]:
mul_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [10]:
mul_d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr1 = np.arange(12).reshape(3,4)

In [12]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
arr1.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## numpy concatenate

In [14]:
ar1 = np.array([
    [1,2],
    [3,5]
])

In [15]:
ar1

array([[1, 2],
       [3, 5]])

In [16]:
ar2 = np.array([
    [5,6],
    [7,8]
])

In [17]:
ar2

array([[5, 6],
       [7, 8]])

In [19]:
ar1

array([[1, 2],
       [3, 5]])

In [20]:
ar2

array([[5, 6],
       [7, 8]])

In [18]:
np.concatenate((ar1,ar2))  #default axis is 0 ---> row wise

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [21]:
ar1

array([[1, 2],
       [3, 5]])

In [22]:
ar2

array([[5, 6],
       [7, 8]])

In [23]:
np.concatenate((ar1,ar2),axis=1)  #column wise concatenation

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [24]:
np.hstack((ar1,ar2))

array([[1, 2, 5, 6],
       [3, 5, 7, 8]])

In [25]:
np.vstack((ar1,ar2))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

## splitting 

In [27]:
ar4 = np.arange(16).reshape(4,4)

In [28]:
ar4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
np.hsplit(ar4,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [30]:
np.vsplit(ar4,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [31]:
arr5 = np.array([[1,2,3],[4,5,6]])

In [38]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
res = np.append(arr5,[100,200,300])

In [37]:
res.reshape(3,3)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [40]:
np.append(arr5,[[500,600,700]],axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [500, 600, 700]])

In [41]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.append(arr5,[[13,14],[15,16]],axis=1)

array([[ 1,  2,  3, 13, 14],
       [ 4,  5,  6, 15, 16]])

## deleting

In [43]:
arr6 = np.array([10,11,12,13,14,15,16,17,18,19])

In [44]:
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
np.delete(arr6,2)

array([10, 11, 13, 14, 15, 16, 17, 18, 19])

In [46]:
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
np.delete(arr6,np.s_[0:2])

array([12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.delete(arr6,[1,3,5])

array([10, 12, 14, 16, 17, 18, 19])

In [51]:
len(arr6)

10

In [52]:
arr7 = arr6.reshape(5,2)

In [53]:
arr7

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [54]:
np.delete(arr7,1,axis=0)  #row wise deletion

array([[10, 11],
       [14, 15],
       [16, 17],
       [18, 19]])

In [55]:
np.delete(arr7,0,axis=1)  #col wise deletion

array([[11],
       [13],
       [15],
       [17],
       [19]])

In [56]:
arr7

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [58]:
new_data =arr7.tolist()

In [59]:
type(new_data)

list

In [60]:
new_data

[[10, 11], [12, 13], [14, 15], [16, 17], [18, 19]]

In [61]:
arr = np.array([
    [2,4,6],
    [1,3,5],
    [9,7,8]
])

In [62]:
arr

array([[2, 4, 6],
       [1, 3, 5],
       [9, 7, 8]])

In [63]:
def calc_data(x):
    return (x[0] - x[-1])

In [66]:
result = np.apply_along_axis(calc_data,1,arr)

In [67]:
result

array([-4, -4,  1])

In [68]:
type(result)

numpy.ndarray

In [69]:
arr8 = np.array([4,5,6,7,8,9,4,5,6,7])

In [70]:
arr8

array([4, 5, 6, 7, 8, 9, 4, 5, 6, 7])

In [71]:
np.unique(arr8)

array([4, 5, 6, 7, 8, 9])

In [72]:
np.unique(arr8,return_index=True)

(array([4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5]))

## mathematical functions

In [73]:
num = np.array([[0,30,45,60,90],[30,45,90,180,270]])

In [74]:
num

array([[  0,  30,  45,  60,  90],
       [ 30,  45,  90, 180, 270]])

In [75]:
np.sin(num)

array([[ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666],
       [-0.98803162,  0.85090352,  0.89399666, -0.80115264, -0.17604595]])

In [76]:
np.cos(num)

array([[ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362],
       [ 0.15425145,  0.52532199, -0.44807362, -0.59846007,  0.98438195]])

In [77]:
np.tan(num)

array([[ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041],
       [-6.4053312 ,  1.61977519, -1.99520041,  1.33869021, -0.17883906]])

In [78]:
arr9 = np.arange(9).reshape(3,3)

In [79]:
arr9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
arr10 = np.array([1,2,3])

In [81]:
arr10

array([1, 2, 3])

In [82]:
np.mod(arr9,arr10)

array([[0, 1, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [86]:
np.remainder(arr9,arr10)

array([[0, 1, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [87]:
np.add(arr9,arr10)

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [89]:
np.subtract(arr9,arr10)

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

In [90]:
np.multiply(arr9,arr10)

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

In [91]:
np.divide(arr9,arr10)

array([[0.        , 0.5       , 0.66666667],
       [3.        , 2.        , 1.66666667],
       [6.        , 3.5       , 2.66666667]])

In [2]:
arr1 = np.array([
    [3,7,5],
    [8,4,3],
    [2,4,9]
])

In [3]:
arr1

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [4]:
np.min(arr1)

2

In [5]:
np.max(arr1)

9

In [6]:
arr2 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

In [7]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.min(arr2,axis=0)

array([1, 2, 3, 4, 5])

In [9]:
np.max(arr2,axis=0)

array([ 6,  7,  8,  9, 10])

In [10]:
np.min(arr2,axis=1)

array([1, 6])

In [11]:
np.max(arr2,axis=1)

array([ 5, 10])

In [13]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
np.mean(arr2)

5.5

In [14]:
np.mean(arr2,axis=0)  # axis 0 ---> columns

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [15]:
np.mean(arr2,axis=1)   # axis 1----> row wise

array([3., 8.])

In [17]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
np.median(arr2)

5.5

In [18]:
arr = np.arange(6)

In [19]:
arr

array([0, 1, 2, 3, 4, 5])

In [20]:
id(arr)

140585050502896

In [21]:
arr2 = arr

In [23]:
id(arr2) == id(arr)

True

In [24]:
np.delete(arr,1)

array([0, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

In [27]:
print(id(arr2))

140585050502896


In [28]:
arr

array([0, 1, 2, 3, 4, 5])

In [29]:
arr.shape = 3,2

In [30]:
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
arr3 = np.arange(10,20)

In [33]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr4 = np.copy(arr3)

In [35]:
id(arr4)

140585052448112

In [36]:
id(arr3)

140585050502608

## sort

In [37]:
arr6 = np.array([
    [3,4],
    [9,1]
])

In [38]:
arr6

array([[3, 4],
       [9, 1]])

In [40]:
np.sort(arr6)

array([[3, 4],
       [1, 9]])

In [42]:
arr6

array([[3, 4],
       [9, 1]])

In [41]:
np.sort(arr6,axis=0)  # axis 0 --> column wise

array([[3, 1],
       [9, 4]])

In [43]:
np.sort(arr6,axis=1)  #axis 1 --> row wise

array([[3, 4],
       [1, 9]])

In [44]:
x = np.array([3,1,2])

In [45]:
x

array([3, 1, 2])

In [46]:
np.argsort(x)

array([1, 2, 0])

## where

In [48]:
arr7 = np.arange(9).reshape(3,3)

In [49]:
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr7[arr7>5]

array([6, 7, 8])

In [52]:
y = np.where(arr7>5)

In [53]:
y

(array([2, 2, 2]), array([0, 1, 2]))

In [54]:
arr7[y]

array([6, 7, 8])

In [55]:
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
condition = np.mod(arr7,2) == 0

In [57]:
np.extract(condition,arr7)

array([0, 2, 4, 6, 8])

## Numpy Strings

In [60]:
res = np.char.add(['hello'],['welcome'])

In [61]:
res

array(['hellowelcome'], dtype='<U12')

In [63]:
np.char.multiply(['hello'],5)

array(['hellohellohellohellohello'], dtype='<U25')

In [64]:
fruit= 'pineapple'

In [65]:
fruit.center(50)

'                    pineapple                     '

In [67]:
np.char.center(['Python'],50,fillchar='*')

array(['**********************Python**********************'], dtype='<U50')

In [68]:
np.char.split('Python Java C++')

array(list(['Python', 'Java', 'C++']), dtype=object)

In [69]:
np.array([100,200,300,400,'hi','bye'])

array(['100', '200', '300', '400', 'hi', 'bye'], dtype='<U21')

In [70]:
lst = ['3 Poori with Subji', 'Chole Bhature [2 Pieces]', '2 Plain Paratha with Subji', '2 Aloo Paratha with Curd', '2 Paneer Paratha with Curd', '2 Onion Paratha with Curd', '2 Gobi Paratha with Curd', '2 Lachha Paratha with Curd', '4 Ghee Roti with Subji', 'Paneer Roll', 'Veg Roll', 'Aloo Roll', 'Paneer Aloo Roll', 'Veg Paneer Roll', 'Mushroom Paneer Roll', 'Bread Omelette [4 Pieces]', '2 Egg Paratha with Curd', 'Boiled Egg', 'Masala Omelette', 'Egg Roll', 'Double Egg Roll', 'Egg Aloo Roll', 'Egg Paneer Roll', 'Chicken Roll', 'Egg Chicken Roll', 'Tawa Roti', 'Ghee Roti', 'Plain Paratha', 'Laccha Paratha', 'Plain Rice', 'Sweet Lassi', 'Salt Lassi']

In [ ]:
lst

In [72]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [74]:
np.random.normal(0,1,25)

array([ 0.29180805, -0.29488176, -0.888097  ,  1.16488976, -0.71914076,
       -2.03272289,  0.98356963,  1.69039115, -0.01542435,  0.55517392,
        1.43021939, -0.93190369,  1.29652811,  0.50602039, -0.52565417,
       -1.21519424, -1.4373158 ,  1.64482045, -1.60688252,  0.32268732,
        1.40683683,  2.22651831,  0.14376639,  1.73165021,  0.48139028])

In [77]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])